name: Daily Bond Yield Tracker

on:
  schedule:
    - cron: '0 21 * * 1-5'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    env:
      FRED_API_KEY: ${{ secrets.FRED_API_KEY }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      MPLBACKEND: Agg

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install libraries
      run: |
        pip install pandas requests boto3 matplotlib python-dotenv

    - name: Run my script
      run: python fred.py

    - name: Run Advanced Yield Spread Pipeline
      run: python Advanced_python_project/Multi_series_yield.py
