name: Monthly Bond Yield Tracker

on:
  schedule:
    # Runs at 5:00 PM EST (21:00 UTC) on the 1st day of every month
    - cron: '0 21 1 * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install libraries
      run: |
        pip install pandas requests python-dotenv

    - name: Run my script
      env:
        FRED_API_KEY: ${{ secrets.FRED_API_KEY }}
      run: python fred.py

    - name: Run Advanced Yield Spread Pipeline
      env:
        FRED_API_KEY: ${{ secrets.FRED_API_KEY }}
      run: python Advanced_python_project/Multi_series_yield.py

    - name: Save CSVs to GitHub (Artifacts)
      uses: actions/upload-artifact@v4
      with:
        name: monthly-bond-data
        path: |
          bonds_data.csv
          advanced_bonds_data.csv
